ALTER SESSION SET CONTAINER=XEPDB1;
ALTER USER APEX_PUBLIC_USER  IDENTIFIED BY Passw0rds ACCOUNT UNLOCK;
ALTER USER APEX_LISTENER IDENTIFIED BY Passw0rds ACCOUNT UNLOCK;
ALTER USER APEX_REST_PUBLIC_USER IDENTIFIED BY Passw0rds ACCOUNT UNLOCK;
